version: '2.2'
services:
    nginx:
        build:
            context: .
            dockerfile: Dockerfile
        image: nginx     # 镜像名称
        container_name: test_ci_cd     # 容器名字
        restart: always     # 开机自动重启
        ports:     # 端口号绑定（宿主机:容器内）
            - '8081:80'
            - '443:443'
       # volumes:      # 目录映射（宿主机:容器内）
         #   - .:/usr/share/nginx/html